on:
  push:
    branches:
      - cicd

jobs:
  deploy1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

  deploy2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display index.html
        run: cat index.html
